### ISSUE TITLE
Feature: Add info --links (or org links) command to display key project/organization URLs

### ISSUE THREAD

**Issue by duizendstra** [contextvibes/cli#15]
**1. Describe the Feature Request:**

We propose adding a new command to the `ContextVibes CLI` that allows users to quickly display a list of important URLs related to the current project or the overarching Context Vibes organization. This would serve as a convenient command-line accessible directory of key resources.

**Example Command Concepts:**

*   `contextvibes info --links`
*   `contextvibes project links`
*   `contextvibes org links` (if specific to org-level links when run in a profile repo)

**2. Problem or Use Case this Feature Solves:**

Currently, key links to repositories, contribution guides, documentation, community forums, issue trackers, etc., are often embedded within `README.MD` files or other documentation. While essential there, developers already in their terminal using `ContextVibes CLI` could benefit from a quicker way to access these URLs without switching to a browser and navigating.

This feature would:
*   Improve discoverability of important project and organization resources.
*   Provide a quick reference for contributors and users directly from the CLI.
*   Reduce the need to hunt through documentation for frequently accessed links.
*   Offer a standardized way for projects using `ContextVibes CLI` to expose their key URLs.

**3. Proposed Functionality & Behavior:**

*   **Configuration Driven:** The list of links should be configurable, likely read from a file within the project or a user's global `ContextVibes CLI` configuration.
    *   *Suggestion 1:* A dedicated file, e.g., `.contextvibes/links.yaml` or `links.json` in the project root.
    *   *Suggestion 2:* A section within the existing `.contextvibes.yaml` project configuration file.
*   **Structured Output:** The command should output the links in a clear, human-readable, and categorized format.
    *   Example output:
        ```
        Context Vibes Initiative Links:

        Repositories:
          - ContextVibes CLI: https://github.com/contextvibes/cli
          - THEA Guidance System: <URL_PLACEHOLDER_FOR_THEA_REPO>
        
        Contribution Guides:
          - CLI Contributing: https://github.com/contextvibes/cli/blob/main/CONTRIBUTING.md
        
        Community & Support:
          - Main Discussion Forum: <URL_PLACEHOLDER_FOR_FORUM>
        ```
*   **Context Awareness (Optional Enhancement):**
    *   If run within a specific project configured with its own links file, it shows project-specific links.
    *   If run from the Context Vibes organization profile repository (or with a global flag), it could show organization-wide links.
    *   A flag like `--org` could force display of org links even from within a project.
*   **Output Format (Optional Enhancement):**
    *   A flag like `--markdown` could output the links in Markdown list format for easy pasting.

**4. Example Configuration (Conceptual YAML for `.contextvibes/links.yaml`):**

```yaml
links:
  - category: "Repositories"
    items:
      - name: "ContextVibes CLI"
        url: "https://github.com/contextvibes/cli"
      - name: "THEA Guidance System"
        url: "https://example.com/thea-repo" # Placeholder - Update with actual link
  - category: "Contribution Guides"
    items:
      - name: "CLI Contributing"
        url: "https://github.com/contextvibes/cli/blob/main/CONTRIBUTING.md"
  - category: "Community & Support"
    items:
      - name: "Report CLI Issues"
        url: "https://github.com/contextvibes/cli/issues"
# ... more categories and links
```

**5. Benefits:**

*   Increased developer convenience and productivity.
*   Better discoverability of essential project/organization resources.
*   Standardized way for projects to share important links via the CLI they already use.
*   Reinforces `ContextVibes CLI` as a central developer assistant tool.

**6. Potential Technical Considerations:**

*   Design of the configuration file schema for links (YAML, JSON, TOML?).
*   Logic for discovering the links configuration file (project-specific vs. global).
*   Implementation of the output formatting.

This feature would align well with the Context Vibes mission of streamlining development and enhancing clarity.
